### ISSUE TITLE
Zentrale Datei mit Headlines und Helpertexten

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cranach-grafiken-gatsby#4]
Wir bräuchten eine zentrale, zweisprachige Datei, aus der wir die Headlines und Helpertexte raus ziehen können.

**Comment by jhfpereira** [comment]
Da wir nun [react-i18next](https://react.i18next.com/) bzw. [i18next](https://www.i18next.com/) für die Internationalisierung nutzen, kann nun an zentraler Stelle, komponentscharf, Übersetzungen eingepflegt werden.

https://github.com/lucascranach/cranach-grafiken-gatsby/tree/master/static/locales
